"""
Django settings for QSHOP project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd1c+a#naix8&__)xuv*g@_@0m#d5u+d0wgc+s3pzyp(#7b+n#!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #添加五个应用
    'manager.apps.ManagerConfig',
    'goods.apps.GoodsConfig',
    'user.apps.UserConfig',
    'store.apps.StoreConfig',
    'home.apps.HomeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'QSHOP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'QSHOP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qshop',
        'USER': 'root',
        'PASSWORD': '426425',
        'HOST': 'localhost',  # 也可以写ip地址
        'PORT': '3306'
    },
    # 'slave': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'qshop',
    #     'USER': 'root',
    #     'PASSWORD': '426425',
    #     'HOST': 'localhost',
    #     'PORT': '3308'
    #
    # },

}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

SESSION_EXPIRE_AT_BROWSER_CLOSE=True  # 关闭浏览器 cookie 失效

STATIC_URL = '/static/'
# 设置静态文件存储路径
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,"static"),
)

# 多媒体文件上传存储路径
MEDIA_ROOT=os.path.join(BASE_DIR,"static")

MEDIA_URL='/media/'   #用于解析静态文件地址



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# smtp服务的邮箱服务器 我用的是163
EMAIL_HOST = 'smtp.163.com'
#smtp服务固定的端口是25，上线时候端口改为994
EMAIL_PORT = 25
#发送邮件的邮箱
EMAIL_HOST_USER = '18737307883@163.com'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'lh1111'
#收件人看到的发件人
EMAIL_FROM = '王炸<18737307883@163.com>'

#上线之后发送邮件需要加
# EMAIL_USE_SSL=True

#主、从数据库的连接
# DATABASE_ROUTERS=['QSHOP.myrouter.DBRouter']
