# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(max_length=20)),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_oprice', models.FloatField()),
                ('goods_xprice', models.FloatField()),
                ('goods_count', models.IntegerField(default=0)),
                ('goods_method', models.CharField(max_length=100)),
                ('goods_info', models.CharField(max_length=100)),
                ('goods_pic', models.ImageField(upload_to='media/uploads')),
                ('goods_address', models.CharField(max_length=50)),
                ('goods_content', models.TextField(verbose_name=30)),
                ('manager', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerMessage')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('type_id', models.AutoField(auto_created=True, db_column='type_id', default='0', primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=30)),
                ('type_sort', models.IntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='type01',
            field=models.ForeignKey(db_column='type_id', default='', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType'),
        ),
    ]
