# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userpass', models.CharField(max_length=32)),
                ('nicheng', models.CharField(max_length=30, null=True)),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('shop_logo', models.ImageField(max_length=50, null=True, upload_to='media/uploads')),
                ('shop_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('add_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='power_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.power')),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('add_user', models.CharField(max_length=50)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='power_roles',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.roles'),
        ),
        migrations.AddField(
            model_name='managermessage',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.roles'),
        ),
    ]
